name: 'Basic Code Quality Checks'

on:
  workflow_call:
    secrets:
      CHECKER_TOKEN:
        description: 'The GITHUB_TOKEN passed from the caller'
        required: true
    outputs:
      pr-title-status:
        description: "The status of the PR title check."
        value: ${{ jobs.check-pr-title.outputs.status }}
      pr-title-summary:
        description: "The summary of the PR title check."
        value: ${{ jobs.check-pr-title.outputs.summary }}
      branch-name-status:
        description: "The status of the branch name check."
        value: ${{ jobs.check-branch-name.outputs.status }}
      branch-name-summary:
        description: "The summary of the branch name check."
        value: ${{ jobs.check-branch-name.outputs.summary }}
      commit-messages-status:
        description: "The status of the commit messages check."
        value: ${{ jobs.check-commits.outputs.status }}
      commit-messages-summary:
        description: "The summary of the commit messages check."
        value: ${{ jobs.check-commits.outputs.summary }}
      commit-messages-report:
        description: "A detailed report for failed commit messages."
        value: ${{ jobs.check-commits.outputs.report }}
      conflicts-status:
        description: "The status of the merge conflicts check."
        value: ${{ jobs.check-conflicts.outputs.status }}
      conflicts-summary:
        description: "The summary of the merge conflicts check."
        value: ${{ jobs.check-conflicts.outputs.summary }}

permissions:
  contents: read
  pull-requests: write
  issues: write

env:
  TYPES: "feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
  MAX_LENGTH: 75

jobs:
  check-commits:
    name: 'Check Commit Messages'
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.status }}
      summary: ${{ steps.check.outputs.summary }}
      report: ${{ steps.check.outputs.report }}
    steps:
      - name: Checkout Caller Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Check Commit Messages Format
        id: check
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: ./.github/scripts/check-commits.sh

  check-conflicts:
    name: 'Check Merge Conflicts'
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.status }}
      summary: ${{ steps.check.outputs.summary }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Check for conflict markers
        id: check
        run: ./.github/scripts/check-conflicts.sh

  check-pr-title:
    name: 'Check PR Title'
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.status }}
      summary: ${{ steps.check.outputs.summary }}
    steps:
      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Check PR Title Format
        id: check
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: ./.github/scripts/check-pr-title.sh

  check-branch-name:
    name: 'Check Branch Name'
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.status }}
      summary: ${{ steps.check.outputs.summary }}
    steps:
      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Check Branch Name Format
        id: check
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: ./.github/scripts/check-branch-name.sh