---
name: Frontend Code Quality Checks
description: >
  Runs Prettier and ESLint checks for frontend code
  quality

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: "20"

outputs:
  prettier-status:
    description: Status of Prettier check (success/failure)
    value: ${{ steps.prettier.outputs.status }}
  prettier-summary:
    description: Summary of Prettier check results
    value: ${{ steps.prettier.outputs.summary }}
  eslint-status:
    description: Status of ESLint check (success/failure)
    value: ${{ steps.eslint.outputs.status }}
  eslint-summary:
    description: Summary of ESLint check results
    value: ${{ steps.eslint.outputs.summary }}

runs:
  using: composite
  steps:
    - name: Set up default Prettier config
      shell: bash
      env:
        TEMPLATE_PATH: ${{ github.action_path }}/templates/.prettierrc.json
      run: ${{ github.action_path }}/scripts/setup-prettier.sh

    - name: Set up default ESLint config
      shell: bash
      env:
        TEMPLATE_PATH: ${{ github.action_path }}/templates/eslint.config.mjs
      run: ${{ github.action_path }}/scripts/setup-eslint.sh

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Dev Dependencies
      shell: bash
      run: |
        if [ -f "package.json" ]; then
          npm install --only=dev
        else
          echo "No package.json found, skipping npm install."
        fi

    - name: Ensure Prettier is installed
      shell: bash
      run: |

        npm list prettier > /dev/null 2>&1 || npm install --no-save prettier

    - name: Ensure ESLint is installed
      shell: bash
      run: |
        npm list eslint > /dev/null 2>&1 || \
          npm install --no-save eslint @eslint/js
        npm list globals > /dev/null 2>&1 || \
          npm install --no-save globals

    - name: Check Prettier Formatting
      id: prettier
      shell: bash
      run: ${{ github.action_path }}/scripts/check-prettier.sh

    - name: Check ESLint
      id: eslint
      shell: bash
      run: ${{ github.action_path }}/scripts/parse-eslint-json.sh
